namespace PRASARNET.Areas.MasterMng.Models
{
    public class EmployeePersonalDetails
    {
        public int EmployeeId { get; set; }
        public string? Pwd { get; set; }
        public int? ReportingOffId { get; set; }
        public int? ReviewingOffId { get; set; }
        public string? AADHARNO { get; set; }
        public string? EMPLOYEE_TYPE { get; set; }
        public string? ParentCadre { get; set; }
        public string? ParentOffice { get; set; }
        public string? PRANNO { get; set; }
        public string? PFID { get; set; }
        public string? EmployeeCode { get; set; }
        public string? EmployeeCode1 { get; set; }
        public string? IRLANONIRLA { get; set; }
        public string? IRLANO { get; set; }
        public bool? OnRoll { get; set; }
        public string? Association { get; set; }
        public int? AssociationReqID { get; set; }
        public bool? AssociationDocUploaded { get; set; }
        public string? UserName { get; set; }
        public int? StationId { get; set; }
        public string? Designation { get; set; }
        public string? FirstName { get; set; }
        public string? MiddleName { get; set; }
        public string? LastName { get; set; }
        public decimal? EL { get; set; }
        public decimal? HPL { get; set; }
        public string? Gender { get; set; }
        public DateTime? DateOfBirthChrist { get; set; }
        public DateTime? DateOfBirthHindu { get; set; }
        public DateTime? DateOfJoining { get; set; }
        public string? Category { get; set; }
        public int? PresentPayScaleandGradePayId { get; set; }
        public int? SubstantivePayScaleandGradePayId { get; set; }
        public DateTime? DateOfJoiningPresentPlaceofPosting { get; set; }
        public bool? IsPersonDisable { get; set; }
        public bool? IsExServiceman { get; set; }
        public string? FathersName { get; set; }
        public string? MothersName { get; set; }
        public string? Nationality { get; set; }
        public DateTime? EligibilityDate { get; set; }
        public string? EligibilityCertificateNo { get; set; }
        public string? BloodGroup { get; set; }
        public string? MotherTongue { get; set; }
        public string? OtherLanguage { get; set; }
        public decimal? Height { get; set; }
        public string? IdentificationMark1 { get; set; }
        public string? IdentificationMark2 { get; set; }
        public string? MobileNo { get; set; }
        public string? EMailId { get; set; }
        public string? NatureOfDisability { get; set; }
        public string? StatusOfDisability { get; set; }
        public decimal? PercentageOfPhysicalHandicapped { get; set; }
        public string? HandicappedCertificateNo { get; set; }
        public string? IssuingAuthority { get; set; }
        public string? PlaceOfIssue { get; set; }
        public string? Place { get; set; }
        public DateTime? IssuingDate { get; set; }
        public string? UniquePostCodeStation { get; set; }
        public string? UniquePostID { get; set; }
        public bool? IsVerified { get; set; }
        public string? BasicDataRemarks { get; set; }
        public string? Remarks { get; set; }
        public string? IpAddress { get; set; }
        public string? HostName { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? ActInctBy { get; set; }
        public DateTime? ActInctDate { get; set; }
        public bool? IsActive { get; set; }
        public bool? PermanentEmployee { get; set; }
        public int? VerifiedBy { get; set; }
        public DateTime? VerifyDate { get; set; }
        public int? SubDesignationTypeID { get; set; }
        public bool? IsTeansfer { get; set; }
        public string? DOCS { get; set; }
        public bool? IsDuplicate { get; set; }
        public bool? IsRelDtFixed { get; set; }
        public bool? HasRetired { get; set; }
        public string? RelieveType { get; set; }
        public DateTime? DT_CONT_STAY_CITY { get; set; }
        public decimal? EL_AVAILED { get; set; }
        public bool? HOS_verified { get; set; }
        public DateTime? Dt_upd_history { get; set; }
        public bool? IsRegister { get; set; }
        public string? EmpActivationCode { get; set; }
        public DateTime? DT_Last_Login { get; set; }
        public string? OTP_MOBILE { get; set; }
        public string? OTP_EMAIL { get; set; }
        public DateTime? DT_OTP { get; set; }
        public DateTime? DT_REG { get; set; }
        public DateTime? DT_USER_ACTIVATION { get; set; }
        public bool? IsUserActivated { get; set; }
        public string? Photoname { get; set; }
        public string? IT_ModeofAppointment { get; set; }
        public string? IT_NICEmail { get; set; }
        public string? IT_EOfficeMobile2 { get; set; }
        public string? IT_NIC_UserID { get; set; }
        public bool? IsNICEmailCreated { get; set; }
        public bool? IsNICEmailCreationAcknowgled { get; set; }
        public bool? IsNICEmailCreatedByNIC { get; set; }
        public int? EmailRequestID { get; set; }
        public string? IT_EOfficeMobile { get; set; }
        public string? EmailCreationRemarks { get; set; }
        public string? EmailCreationStatus { get; set; }
        public string? PostedAt { get; set; }
        public bool? WhetherDDGAbove { get; set; }
        public bool? WhetherDDGAbove1 { get; set; }
        public DateTime? LastUpdatedE_C { get; set; }
        public string? IT_Service { get; set; }
        public string? IT_Cadre { get; set; }
        public bool? ContributingEmp { get; set; }
        public decimal? Pmcaresdonation { get; set; }
        public bool? New_Emp { get; set; }
        public DateTime? LastpwdChangedOn { get; set; }
        public string? Fname1 { get; set; }
        public string? Mname1 { get; set; }
        public string? Lname1 { get; set; }
        public string? Service { get; set; }
        public string? Cadre { get; set; }
        public string? Batch { get; set; }
    }
}
